# Generated by Django 3.1.8 on 2021-06-04 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210604_1813'),
        ('customers', '0002_auto_20210604_1817'),
    ]

    operations = [
    ]
